### PR TITLE
welcome wrap-format!

### LINKED ISSUE #374: when two routes file  use (api xxx
## Library Version(s)
2.0.0-alpha19
## Problem

when two routes file  use (api xxx   
when POST :body-params  [name desc]  
the first routes is ok  but second report 
```
{"schema":"{:customerid Any, :description Any}","errors":"(not (map? nil))","type":"compojure.api.exception/request-validation","coercion":"schema","value":null,"in":["request","body-params"]}
```

### PR DESCRIPTION
**Pull request by ikitommi**
fixes #374.

### CODE REVIEW

File: src/compojure/api/middleware.clj [hunk 1]
```diff
@@ -286,3 +289,27 @@
          wrap-nested-params
          ;; 4.5µs => 7.1µs (+50%)
          wrap-params))))
+
+(defn wrap-format
+  "Muuntaja format middleware. Can be safely mounted on
```
Comment (Deraen) [inline src/compojure/api/middleware.clj]: Something is missing
